# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyfr < Formula
  desc "CLI for the CYFR sandboxed WASM runtime"
  homepage "https://cyfr.run"
  version "1.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.7.0/cyfr_1.7.0_darwin_amd64.tar.gz"
      sha256 "0ddb0fcb82736452a61806019a2238944d64b8dbde86cc6704631ca3735387aa"

      define_method(:install) do
        bin.install "cyfr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.7.0/cyfr_1.7.0_darwin_arm64.tar.gz"
      sha256 "53b70e4aeedc231083353a4dbb641cd70f887e171c082f5ef8e5b4ff12adb63d"

      define_method(:install) do
        bin.install "cyfr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.7.0/cyfr_1.7.0_linux_amd64.tar.gz"
      sha256 "57e8f71a4ec29dfb147b3ce586e6d8d9a2be0861aa2714edeb1a59afb152596d"
      define_method(:install) do
        bin.install "cyfr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.7.0/cyfr_1.7.0_linux_arm64.tar.gz"
      sha256 "afc2014f435b1152b2261b7d3b68d3ae6f6ca5062065c6325ffeace5278eaa3e"
      define_method(:install) do
        bin.install "cyfr"
      end
    end
  end
end
