# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cyfr < Formula
  desc "CLI for the CYFR sandboxed WASM runtime"
  homepage "https://cyfr.run"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.2.1/cyfr_1.2.1_darwin_amd64.tar.gz"
      sha256 "9bc185b532ee04303ffdc34ee1c6b2fc1eb5014ea2fd0a57f4cc5bd5cbf763ae"

      define_method(:install) do
        bin.install "cyfr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.2.1/cyfr_1.2.1_darwin_arm64.tar.gz"
      sha256 "6953bfda4992f223540c1fc486fa6aa645f2a1481704d863b0cb9fe0f913d666"

      define_method(:install) do
        bin.install "cyfr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.2.1/cyfr_1.2.1_linux_amd64.tar.gz"
      sha256 "d8b199731421e6d26c393f2a70e7bf4230a398e82ca7cba0381bb9120e76ce19"
      define_method(:install) do
        bin.install "cyfr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyfrworks/cyfr/releases/download/v1.2.1/cyfr_1.2.1_linux_arm64.tar.gz"
      sha256 "31794669814b5d491618182636adcd630cb64af9ca7ba2b4e3fb7b984b1c6162"
      define_method(:install) do
        bin.install "cyfr"
      end
    end
  end
end
