# This file was generated by GoReleaser. DO NOT EDIT.
cask "cyfr" do
  name "cyfr"
  desc "CLI for the CYFR sandboxed WASM runtime"
  homepage "https://cyfr.run"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cyfr"

  on_macos do
    on_intel do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_darwin_amd64.tar.gz"
      sha256 "402ab7a9b1f9ce41d600ea52bf530180c945af048d825d01086eb403feaf8536"
    end
    on_arm do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_darwin_arm64.tar.gz"
      sha256 "051f1f8ba3ec2022a8c701ca5a07ccb6354102e6fcbd465234c4d774c4ba3638"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_linux_amd64.tar.gz"
      sha256 "f24d0e14219bfe0d88e62049faed9ba4c0af0ab8b3544dee82d8550a5faf3268"
    end
    on_arm do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_linux_arm64.tar.gz"
      sha256 "b1d3f83706f8671791938ceb2223909ad8cadf10867210a72b8e48f089151411"
    end
  end

  # No zap stanza required
end
