# This file was generated by GoReleaser. DO NOT EDIT.
cask "cyfr" do
  name "cyfr"
  desc "CLI for the CYFR sandboxed WASM runtime"
  homepage "https://cyfr.run"
  version "0.16.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cyfr"

  on_macos do
    on_intel do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_darwin_amd64.tar.gz"
      sha256 "03d3fd7ed110a23cfff2f4040babd12df57cf0d1fd6438b9040ba4eb5ecb16ca"
    end
    on_arm do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_darwin_arm64.tar.gz"
      sha256 "fbf62f2d2a70fa9fed45ba1418f5450697b9ed73c76f51dae10162343b6795e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_linux_amd64.tar.gz"
      sha256 "5e16c1f403ff490a363817497508b429376d002e94d3bbb352e95e9a26399425"
    end
    on_arm do
      url "https://github.com/cyfrworks/cyfr/releases/download/v#{version}/cyfr_#{version}_linux_arm64.tar.gz"
      sha256 "d19c5c57df33606a218b408b5d8ba4c8c3bedb0b83155692e892e566166c625c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cyfr"]
    end
  end

  # No zap stanza required
end
